import os

# ak sk:
ALI_CLOUD_ACCESS_KEY_ID = os.environ['ALI_CLOUD_ACCESS_KEY_ID']
ALI_CLOUD_ACCESS_KEY_SECRET = os.environ['ALI_CLOUD_ACCESS_KEY_SECRET']

# instance info:
ADBPG_INSTANCE_ID = os.environ.get('ADBPG_INSTANCE_ID')
ADBPG_INSTANCE_REGION = os.environ.get('ADBPG_INSTANCE_REGION')

ALI_CLOUD_ENDPOINT = os.environ.get('ALI_CLOUD_ENDPOINT')
